[build-system]
requires = ["uv==0.5.29"]
build-backend = "uv"

[project]
name = "buildsign-dev"
version = "0.0.0"
dependencies = [
  "cappa>=0.26.4",
  "dulwich>=0.22.1",
  "pydantic-settings>=2.5.2",
  "pydantic>=2.9.1",
  "python-dotenv>=1.0.1",
]
[project.scripts]
"buildsign-dev" = "buildsign_dev.__main__:main"
[project.optional-dependencies]
docs = [
  "devtools>=0.12.2",
  "docutils>=0.21.2",
  "geopandas>=0.14.3",
  "ipython>=8.26.0",
  "matplotlib>=3.7.2",
  "more-itertools>=10.4.0",
  "myst-parser>=3.0.1",
  "nbformat>=5.10.4",
  "numpy>=1.24.4",
  "numpydoc>=1.7.0",
  "pandas[hdf5,performance]>=2.2.2",
  "ruamel-yaml>=0.18.6",
  "seaborn>=0.13.2",
  "shapely>=2.0.6",
  "sphinx>=7.3.7",
  "sympy>=1.12",
  "trackpy>=0.6.2",
]
tests = ["pytest-harvest>=1.10.5", "pytest>=8.2.2"]

[tool.fawltydeps]
deps = ["packages/_dev/pyproject.toml"]
code = ["packages/_dev", "tests"]
ignore_undeclared = ["hello"]
[tool.fawltydeps.custom_mapping]
ruamel-yaml = ["ruamel"]
