[build-system]
requires = ["uv==0.5.29"]
build-backend = "uv"

[project]
name = "buildsign-dev"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = ["cappa>=0.26.4", "dulwich>=0.22.1"]
[project.scripts]
"buildsign-dev" = "buildsign_dev.__main__:main"

[tool.fawltydeps]
deps = ["packages/_dev/pyproject.toml"]
code = ["packages/_dev", "tests"]
ignore_undeclared = ["hello"]
[tool.fawltydeps.custom_mapping]
