[build-system]
requires = ["uv==0.5.29"]
build-backend = "uv"

[project]
name = "dev"
version = "0.0.0"
dependencies = ["cappa>=0.26.3"]
[project.scripts]
"dev" = "dev.__main__:main"

[tool.fawltydeps]
deps = ["src/_dev/pyproject.toml"]
code = ["src/_dev", "tests"]
ignore_undeclared = ["hello"]
