[build-system]
requires = ["uv==0.5.29"]
build-backend = "uv"

[project]
name = "buildsign-dev"
version = "0.0.0"
dependencies = ["cappa>=0.26.3"]
[project.scripts]
"buildsign-dev" = "dev.__main__:main"

[tool.fawltydeps]
deps = ["packages/_dev/pyproject.toml"]
code = ["packages/_dev", "tests"]
ignore_undeclared = ["hello"]
