[build-system]
requires = ["uv==0.5.29"]
build-backend = "uv"

[project]
name = "hello"
version = "0.0.0"
dependencies = ["cappa>=0.26.4"]
[project.scripts]
"hello" = "hello.__main__:main"

[tool.fawltydeps]
deps = ["packages/hello/pyproject.toml"]
code = ["packages/hello"]
