[build-system]
requires = ["uv-build==0.6.16"]
build-backend = "uv_build"

[project]
name = "hello"
version = "0.0.0"
dependencies = ["cappa>=0.26.4"]
requires-python = ">=3.12"
[project.scripts]
"hello" = "hello.__main__:main"

[tool.fawltydeps]
deps = ["packages/hello/pyproject.toml"]
code = ["packages/hello"]
